import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Auth WebAPP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.text_center} >Auth WebAPP</h1>
        <p className={styles.text_center}>
          This is a web application that uses the Ethereum blockchain to authenticate users.
        </p>
        <div className={styles.btns} >
          <Link className={styles.btn} href="/Auth/Signup">Inscription</Link>
          <Link className={styles.btn_bis} href="/Auth/Signin">Connexion</Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <p>Copright 2024 - Auth WebAPP</p>
      </footer>
    </div>
  )
}
